---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
- name: "Set shell to {{ default_shell }}"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    state: present
    shell: "{{ default_shell }}"
    force: no
