---
- name: Install auto updates
  become: true
  ansible.builtin.dnf:
    name: "dnf-automatic"
    state: present
- name: Enable timer for dnf-automatic
  become: true
  ansible.builtin.systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: yes
