---
- name: Set authorized keys from github
  ansible.builtin.shell:
    cmd: "curl https://github.com/{{ github_user }}.keys > {{ ansible_env.HOME }}/.ssh/authorized_keys"
- name: Copy sshd config
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/sshd_config"
    dest: /etc/ssh/sshd_config.d/additions.conf
    owner: root
    group: root
    mode: 0600
- name: Restart sshd service
  become: true
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: yes
