---
- name: Remove existing docker packages
  become: true
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: absent
  vars:
    docker_packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- name: Install dnf-plugins-core to manage DNF repository
  become: true
  ansible.builtin.dnf:
    name:  dnf-plugins-core
    state: present

- name: Add docker repo
  become: true
  ansible.builtin.command:
    cmd: "dnf config-manager --add-repo \
  https://download.docker.com/linux/fedora/docker-ce.repo"
    warn: false

- name: Install docker engine
  become: true
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: latest
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user "{{ ansible_user_id }}" to group docker
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: yes

- name: Start docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
