---
- name: Install cargo packages
  ansible.builtin.shell:
    cmd: "cargo install {{ item }}"
    executable: /usr/bin/fish
  register: cargo_output
  changed_when: "'already installed' not in cargo_output.stderr"
  loop: "{{ cargo_packages }}"
