---
- name: Create npm global path
  ansible.builtin.file:
    path: ~/.npm/global
    state: directory
    mode: '0755'
- name: Set npm global path
  ansible.builtin.command: npm config set prefix '~/.npm/global'
- name: Install npm packages
  community.general.npm:
    name: "{{ item }}"
    state: present
    production: yes
    global: yes
  loop: "{{ npm_packages }}"
